# .github/workflows/manual-image-scan.yml
name: Manual Container Image Scan

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image to scan (e.g., alpine:3.18, mydockerhub/myapp:latest)'
        required: true
        type: string
        default: 'alpine:latest'
      severity_level:
        description: 'Minimum severity to fail on (e.g., HIGH,CRITICAL)'
        required: false
        type: string
        default: 'HIGH,CRITICAL'

jobs:
  call_reusable_scanner:
    name: Trigger Image Scan
    # Call the reusable workflow IN THE SAME REPOSITORY at the current ref (e.g., main branch)
    # For production, use a specific tag or commit SHA instead of 'main' like '@v1.0' or '@sha...'
    uses: ./.github/workflows/scan-image-reusable.yml@main
    with:
      image-to-scan: ${{ github.event.inputs.image_name }}
      fail-on-severity: ${{ github.event.inputs.severity_level }}
    # If the reusable workflow needed secrets (e.g., for private registry login)
    # secrets: inherit
